# Generated by prepare_run_env.sh mode=cold run=P2-cold-normal-error at 2026-10-07T03:38:44+00:00
export RCA_RUN_ID='P2-cold-normal-error'
export RCA_CACHE_ROOT='/workspace/rca-caches/P2-cold-normal-error'
export TRITON_CACHE_DIR='/workspace/rca-caches/P2-cold-normal-error/triton'
export TORCHINDUCTOR_CACHE_DIR='/workspace/rca-caches/P2-cold-normal-error/torchinductor'
export VLLM_CACHE_ROOT='/workspace/rca-caches/P2-cold-normal-error/vllm'
export XDG_CACHE_HOME='/workspace/rca-caches/P2-cold-normal-error/xdg'
export TRITON_HOME='/workspace/rca-caches/P2-cold-normal-error/triton-home'
export HF_HOME='/workspace/rca-caches/P2-cold-normal-error/hf'
# ROCm 7.14 environment contract (docs/02-environment.md): isolation from
# host /opt/rocm 7.2 toolchain and old /opt/venv stack.
export VENV_QDN_RCA='/workspace/venv-qwen-gdn-rca'
export ROCM_PATH='/workspace/venv-qwen-gdn-rca/lib/python3.12/site-packages/_rocm_sdk_devel'
export HIP_PATH='/workspace/venv-qwen-gdn-rca/lib/python3.12/site-packages/_rocm_sdk_devel'
export CMAKE_PREFIX_PATH='/workspace/venv-qwen-gdn-rca/lib/python3.12/site-packages/_rocm_sdk_devel'
export LD_LIBRARY_PATH='/workspace/venv-qwen-gdn-rca/lib/python3.12/site-packages/_rocm_sdk_devel/lib'
export PATH='/workspace/venv-qwen-gdn-rca/lib/python3.12/site-packages/_rocm_sdk_devel/bin:/workspace/venv-qwen-gdn-rca/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
unset PYTHONPATH
export PYTHONNOUSERSITE=1
