#!/bin/bash
# Process-safe cache isolation harness (replaces direct use of reset_caches.sh).
#
# Usage:
#   prepare_run_env.sh cold  <RUN_ID>   # rm -rf cache root, create empty dirs, emit run-env.sh
#   prepare_run_env.sh warm  <RUN_ID>   # verify existing dirs, emit run-env.sh
#
# Output:
#   evidence/runs/<RUN_ID>/run-env.sh   # MUST be sourced by the launching shell
#   evidence/runs/<RUN_ID>/cache-before.txt
#
# The caller then does:
#     source evidence/runs/<RUN_ID>/run-env.sh
#     python scripts/preflight_cache_env.py   # hard-fails on contamination
#     <launch vllm>
set -euo pipefail
MODE="${1:?cold|warm}"
RUN_ID="${2:?run id}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="/workspace/rca-caches/${RUN_ID}"
RUNDIR="${REPO_ROOT}/evidence/runs/${RUN_ID}"
mkdir -p "$RUNDIR"

emit_env_sh() {
  VENV=/workspace/venv-qwen-gdn-rca
  DEV=$VENV/lib/python3.12/site-packages/_rocm_sdk_devel
  cat > "${RUNDIR}/run-env.sh" <<EOF
# Generated by prepare_run_env.sh mode=${MODE} run=${RUN_ID} at $(date -Is)
export RCA_RUN_ID='${RUN_ID}'
export RCA_CACHE_ROOT='${ROOT}'
export TRITON_CACHE_DIR='${ROOT}/triton'
export TORCHINDUCTOR_CACHE_DIR='${ROOT}/torchinductor'
export VLLM_CACHE_ROOT='${ROOT}/vllm'
export XDG_CACHE_HOME='${ROOT}/xdg'
export TRITON_HOME='${ROOT}/triton-home'
export HF_HOME='${ROOT}/hf'
# ROCm 7.14 environment contract (docs/02-environment.md): isolation from
# host /opt/rocm 7.2 toolchain and old /opt/venv stack.
export VENV_QDN_RCA='${VENV}'
export ROCM_PATH='${DEV}'
export HIP_PATH='${DEV}'
export CMAKE_PREFIX_PATH='${DEV}'
export LD_LIBRARY_PATH='${DEV}/lib'
export PATH='${DEV}/bin:${VENV}/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
EOF
}

case "$MODE" in
  cold)
    rm -rf "$ROOT"
    mkdir -p "$ROOT"/{triton,torchinductor,vllm,xdg,triton-home,hf}
    emit_env_sh
    ;;
  warm)
    for d in triton torchinductor vllm xdg triton-home hf; do
      [ -d "$ROOT/$d" ] || { echo "warm mode: missing $ROOT/$d (run cold first)" >&2; exit 1; }
    done
    emit_env_sh
    ;;
  *) echo "bad mode: $MODE" >&2; exit 1;;
esac

# cache-before manifest: per-directory file count and byte size
{
  echo "# cache-before $(date -Is) mode=${MODE} run=${RUN_ID}"
  for d in triton torchinductor vllm xdg triton-home hf; do
    p="$ROOT/$d"
    if [ "$MODE" = cold ]; then
      echo "$d 0 files 0 bytes  (must be empty)"
      find "$p" -mindepth 1 | wc -l | awk -v d="$d" '$1!=0{print "NONEMPTY:"d; exit 1}'
    else
      n=$(find "$p" -type f 2>/dev/null | wc -l)
      b=$(du -sb "$p" 2>/dev/null | awk '{print $1}')
      echo "$d $n files $b bytes"
    fi
  done
} > "${RUNDIR}/cache-before.txt"

echo "run-env.sh + cache-before.txt written for ${RUN_ID} (${MODE})"
echo "next: source ${RUNDIR}/run-env.sh && python ${REPO_ROOT}/scripts/preflight_cache_env.py"
